sequenceDiagram
    participant Browser
    participant Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate Server
    Server-->>Browser: HTML document (status 200)
    deactivate Server
    Note right of Browser: Browser renders the HTML page.

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate Server
    Server-->>Browser: CSS file (status 200)
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate Server
    Server-->>Browser: JavaScript file (status 200)
    deactivate Server
    Note right of Browser: Browser starts executing JavaScript when the submit button is pressed.

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate Server
    Server-->>Browser: [{ "content": "SPA page", "date": "2023-05-10" }, ... ]
    deactivate Server
    Note right of Browser: Browser executes the event to render only the notes again.
